src/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from . import db
from sqlalchemy.sql import func


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    notes = db.relationship('Note')


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(1000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


db = SQLAlchemy()
DB_NAME = 'base_dados.db'


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'filipe'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .accounts import accounts

    from .models import User, Note

    create_database(app)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'accounts.login'

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(accounts, url_prefix='/accounts')

    return app


def create_database(app):
    if not path.exists('src/' + DB_NAME):
        db.create_all(app=app)
        print("DATABASE CREATED")

src/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import User, Note
from . import db

#blue print to create the endpoints
views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def index():
    if request.method == 'POST':
        note = request.form.get('note')
        user_id = current_user.id
        new_note = Note(text=note, user_id=user_id)
        db.session.add(new_note)
        db.session.commit()
        flash('Note Added successfuly', category='success')
    
    all_notes = Note.query.filter_by(user_id=current_user.id)

    return render_template('index.html', notes=all_notes)

@views.route('/delete-note/<string:id>', methods=['POST'])
@login_required
def delete_note(id):
    if request.method == 'POST':
        note_delete = Note.query.get(id)
        if note_delete:
            if note_delete.user_id == current_user.id:
                db.session.delete(note_delete)
                db.session.commit()

    return redirect(url_for('views.index'))

src/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
        {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/accounts/logout">Logout</a>
          <a class="nav-item nav-link" id="">Welcome {{ current_user.first_name }}</a>
        {% else %}
          <a class="nav-item nav-link" id="login" href="/accounts/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/accounts/register">Sign Up</a>
        {% endif %}
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}  
    {% for category, message in messages %}
    {% if category == 'error'  %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>

    {% else %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">{% block content %}{% endblock content %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<h1 align="center">Your notes</h1>
<ul class="list-group list-group-flush" id="notes">
{% for note in notes %}
  <li class="list-group-item">
    {{ note.text }}
    <form action="{{ url_for('views.delete_note', id=note.id) }}" method='POST'>
    <button type="submit" class="close">
      <span aria-hidden="true">&times;</span>
    </button>
    </form>
  </li>
{% endfor %}
</ul>

<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>
{% endblock content %}

src/templates/login.html
{% extends 'base.html' %}
{% block title %}Register Page{% endblock title %}
{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock content %}

src/templates/register.html
{% extends 'base.html' %}
{% block title %}Register Page{% endblock title %}
{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="first_name">First Name</label>
      <input
        type="text"
        class="form-control"
        id="first_name"
        name="first_name"
        placeholder="Enter first name"
      />
    </div>
    <div class="form-group">
        <label for="last_name">Last Name</label>
        <input
          type="text"
          class="form-control"
          id="last_name"
          name="last_name"
          placeholder="Enter last name"
        />
      </div>
    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Enter password"
      />
    </div>
    <div class="form-group">
      <label for="password2">Password (Confirm)</label>
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2"
        placeholder="Confirm password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock content %}